#!/usr/bin/env bash

# /-------------------------------------------------------------------------------
# | Utilities
# |-------------------------------------------------------------------------------
# /

# come back here quickly
alias shortcuts="vim ~/.aliases"

# ls replacement
source ~/.exa-colors
alias ls="exa -lb --time-style=long-iso --group-directories-first -a"
alias l="ls"
# alias ll="exa -lbGF --git --group-directories-first"
alias la="exa -lbhHigUmuSa@ --time-style=long-iso --git --color-scale"

alias cat="ccat"

# copy current working dir
alias cpwd="pwd | tr -d '\n' | pbcopy"

# because you can't go back from a rm -rf...
alias rm="echo Dude, stop using rm! Use \'trash\' or, if you insist, \'/bin/rm\'."
alias trash="trash-put"

# /-------------------------------------------------------------------------------
# | Git is great
# |-------------------------------------------------------------------------------
# /
alias gs='git status'
alias nah="git reset --hard head && git clean -fd"

alias gstash="git add . && git commit -m 'stash'"
alias gpop="git reset --soft head~1 && git reset head"
alias gsu='git branch --set-upstream-to=origin/$(git rev-parse --abbrev-ref HEAD)'
alias gpu='git push -u origin $(git rev-parse --abbrev-ref HEAD)'

# destructive, ye' be warned
grho() {
    branch=$(git branch | grep \* | cut -d ' ' -f2)
    git reset --hard origin/$branch
}

gri() {
    git rebase -i head~$1
}

# git diff without the git
gdiff() {
    git diff --no-index $1 $2 | diff-so-fancy | less
}

alias grc="git rebase --continue"
alias grs="git rebase --skip"

# /-------------------------------------------------------------------------------
# | Jumping around
# |-------------------------------------------------------------------------------
# /
alias home='cd ~'
alias desk='cd ~/desktop'
alias dotfiles='cd ~/.dotfiles'
alias code='cd ~/code'
alias emd='cd ~/.emacs.d'
alias dmd='cd ~/.doom.d'

# /-------------------------------------------------------------------------------
# | Docker
# |-------------------------------------------------------------------------------
# /

alias c="docker-compose"

# launch portainer (gui to manage docker)
alias portainer="docker volume create portainer_data &&  docker run -d -p 9000:9000 -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer"

# /-------------------------------------------------------------------------------
# | K8s
# |-------------------------------------------------------------------------------
# /

alias kl="kubectl" # bc i always misspell that one

# /-------------------------------------------------------------------------------
# | PHP
# |-------------------------------------------------------------------------------
# /

alias phpunit='vendor/bin/phpunit'
alias pu='phpunit'
alias pf="phpunit --filter"

# quick php/laravel REPL
alias tinker='php ~/code/laravel/artisan tinker'

# laravel stuff
alias art='php artisan'

# /-------------------------------------------------------------------------------
# | LiveIntent
# |-------------------------------------------------------------------------------
# /
tunnel() {
    ssh -i ~/.ssh/li.id_rsa -L $2:$1-rds.liveintenteng.com:3306 $1-bastion
}
