#!/usr/bin/env bash

export FZF_DEFAULT_OPTS='--layout=reverse'

# /-------------------------------------------------------------------------------
# | The colors!
# |-------------------------------------------------------------------------------
# /
 export FZF_DEFAULT_OPTS=$FZF_DEFAULT_OPTS'
 --color=fg:#f1f1f0,bg:#171c20,hl:#88c0d0
 --color=fg+:#88c0d0,bg+:#292f38,hl+:#88c0d0
 --color=info:#303d4a,prompt:#50fa7b,pointer:#f1f1f0
 --color=marker:#b46ead,spinner:#303d4a,header:#87afaf'

# /-------------------------------------------------------------------------------
# | Git
# |-------------------------------------------------------------------------------
# /
alias glGraph='git log --graph --color=always --format="%Cred%h%Creset - %s %Cgreen(%cr) %C(bold blue)<%an>%Creset" "$@"'
_gitLogLineToHash="echo {} | grep -o '[a-f0-9]\{7\}' | head -1"
_viewGitLogLine="$_gitLogLineToHash | xargs -I % sh -c 'git show --color=always % | delta'"

# gco - checkout git branch (including remote branches), sorted by most recent commit, limit 50 last branches
unalias gco 2> /dev/null
gco() {
  if [[ ! -z $@ ]]; then git checkout "$@"; return; fi

  local branches branch
  branches=$(git for-each-ref --count=50 --sort=-committerdate --format="%(refname:short)") &&
  branch=$(echo "$branches" |
           fzf-tmux -d $(( 2 + $(wc -l <<< "$branches") )) +m) &&
  git checkout $(echo "$branch" | sed "s/.* //" | sed "s#remotes/[^/]*/##" | sed "s/.*\///")
}

# glo - Replacement for git log, shows previews, allows selecting commits to view further
unalias glo 2> /dev/null
glo() {
    glGraph |
        fzf --no-sort --no-mouse --reverse --tiebreak=index --no-multi \
            --ansi --preview="$_viewGitLogLine" \
                --header "enter to view, ctrl-y to copy hash" \
                --bind "enter:execute:$_viewGitLogLine   | less -R" \
                --bind "ctrl-y:execute:$_gitLogLineToHash | pbcopy"
}

# /-------------------------------------------------------------------------------
# | Node
# |-------------------------------------------------------------------------------
# /
yr() {
  local cmd

  cmd=$(cat package.json | jq -r '.scripts | keys[]' | fzf) &&
      yarn run $cmd
}

# the opposite of glo (shows incoming changes)
alias gro="glo ..@{u}"
# /-------------------------------------------------------------------------------
# | AWS
# |-------------------------------------------------------------------------------
# /
au() {
  local profile

  profile=$(aws configure list-profiles | fzf) &&
      export AWS_PROFILE=$profile
}

# /-------------------------------------------------------------------------------
# | Kubernetes
# |-------------------------------------------------------------------------------
# /

ku() {
  local context

  context=$(kubectl config get-contexts -o name | fzf) &&
      kubectl config use-context $context
}

klog() {
  local pod

  pod=$(kubectl get pods --all-namespaces --no-headers | fzf) &&
      print -z "$(echo $pod | awk '{print "kubectl logs -n " $1 " " $2}')"
}

kex() {
  local pod

  pod=$(kubectl get pods --all-namespaces --no-headers | fzf) &&
      print -z "$(echo $pod | awk '{print "kubectl -n " $1 " exec -it " $2 " bash"}')"
}

# /-------------------------------------------------------------------------------
# | LiveIntent
# |-------------------------------------------------------------------------------
# /
li() {
  if [[ -n "$@" ]]; then platformer "$@"; return; fi

  local commands command
  commands=$(platformer list -n 2>&1 | awk '{print $1}')
  command=$(echo "$commands" | fzf --ansi \
    --preview="platformer {} --help" \
    --header "enter to select") &&

  print -z "platformer $command"
}

# /-------------------------------------------------------------------------------
# | System
# |-------------------------------------------------------------------------------
# /
# env - Replacment for env
alias env="/usr/bin/env | fzf"
