#!/usr/bin/env sh

DOTFILES="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cp $DOTFILES/env.example $HOME/.env

# git
ln -sf $DOTFILES/git/gitconfig $HOME/.gitconfig
ln -sf $DOTFILES/git/gitignore_global $HOME/.gitignore_global

# ssh
ln -sf $DOTFILES/ssh/config $HOME/.ssh/config

# karabiner
mkdir -p $HOME/.config
ln -sf $DOTFILES/karabiner $HOME/.config

# zsh
ln -sf $DOTFILES/zsh/zshrc $HOME/.zshrc

# starship
ln -sf $DOTFILES/starship/starship.toml $HOME/.config

# neovim
rm -rf $HOME/.config/nvim
ln -s $DOTFILES/nvim $HOME/.config/nvim

# vscode
ln -sf $DOTFILES/vscode/settings.json $HOME/Library/Application\ Support/Code/User/settings.json
ln -sf $DOTFILES/vscode/keybindings.json $HOME/Library/Application\ Support/Code/User/keybindings.json

# atuin
rm -rf $HOME/.config/atuin
ln -s $DOTFILES/atuin $HOME/.config/atuin

# doom
rm -rf $HOME/.config/doom
ln -s $DOTFILES/doom $HOME/.config/doom

# tmux
ln -sf $DOTFILES/tmux/tmux.conf $HOME/.tmux.conf

# aerospace
rm -rf $HOME/.config/aerospace
ln -s $DOTFILES/aerospace $HOME/.config/aerospace

# skhd & yabai
# ln -sf $DOTFILES/yabai/yabairc $HOME/.yabairc
# ln -sf $DOTFILES/skhd/skhdrc $HOME/.skhdrc

touch $HOME/.hushlogin

# scripts
mkdir -p $HOME/.local/bin
ln -sf $DOTFILES/scripts/display_is_ultrawide $HOME/.local/bin/display_is_ultrawide
