#!/usr/bin/env sh

DOTFILES="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

mkdir -p $HOME/.config/git
ln -sf $DOTFILES/config/git/config $HOME/.config/git/
ln -sf $DOTFILES/config/git/ignore $HOME/.config/git/

mkdir -p $HOME/.config/iterm2
ln -sf $DOTFILES/config/iterm2/com.googlecode.iterm2.plist $HOME/.config/iterm2/

mkdir -p $HOME/.config/karabiner
ln -sf $DOTFILES/config/karabiner/assets $HOME/.config/karabiner/
ln -sf $DOTFILES/config/karabiner/karabiner.json $HOME/.config/karabiner/

ln -sf $DOTFILES/config/ssh/config $HOME/.ssh/

ln -sf $DOTFILES/config/zsh $HOME/.config/
ln -sf $DOTFILES/config/zsh/p10k.zsh $HOME/.p10k.zsh
ln -sf $DOTFILES/config/zsh/zshrc $HOME/.zshrc

rm -rf $HOME/.config/nvim
ln -s $DOTFILES/config/nvim $HOME/.config/nvim

touch $HOME/.hushlogin

export XDG_CACHE_HOME="$HOME/.cache"; mkdir -p $XDG_CACHE_HOME
export XDG_CONFIG_HOME="$HOME/.config"; mkdir -p $XDG_CONFIG_HOME
export XDG_DATA_HOME="$HOME/.local/share"; mkdir -p $XDG_DATA_HOME
export XDG_STATE_HOME="$HOME/.local/state"; mkdir -p $XDG_STATE_HOME

if [ ! -f $HOME/.env ]; then
    cp .env.example $HOME/.env
fi
