if [ -f $HOME/.env ]; then
    set -o allexport; source $HOME/.env; set +o allexport
fi

# we try to follow it a little bit but not really
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"

export ZSH_COMPDUMP="${ZSH_CACHE_DIR}/.zcompdump-${(%):-%m}-${ZSH_VERSION}"

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

typeset -U path
path=(
    /opt/homebrew/bin
    $XDG_CONFIG_HOME/emacs/bin
    $HOME/.local/bin
    vendor/bin
    $path
)

################
source /opt/homebrew/share/antigen/antigen.zsh

antigen bundle zsh-users/zsh-autosuggestions
antigen bundle jeffreytse/zsh-vi-mode

antigen theme romkatv/powerlevel10k

antigen apply
##################

export ZVM_INSERT_MODE_CURSOR=$ZVM_CURSOR_BLINKING_BEAM

###########################
export EDITOR=nvim
export GIT_EDITOR=nvim

alias vim="nvim"
alias g="git"
alias gs="git status"

alias cat="bat"

## TODO make these smarter functions
alias ga="git add"
alias gap="git add --patch"
alias gc="git commit"
alias gp="git push"
alias gd="git diff"
alias gco="git checkout"
alias nah="git reset --hard head && git clean -fd"


diff() {
  /usr/bin/diff -u "$1" "$2" | delta  \
    --side-by-side \
    --right-arrow="→" \
    --file-decoration-style="brightblack ul" \
    --hunk-header-style="" \
    --line-numbers-left-format="{nm} " \
    --line-numbers-right-format=" │ {np} " \
    --line-numbers-right-style="brightblack"
}

alias dotfiles="cd ~/Areas/dotfiles"
alias dmd="cd ~/.config/doom"

alias home="cd ~"
alias desk="cd ~/Desktop"
alias p="cd ~/Projects"
alias a="cd ~/Areas"
alias exp="cd ~/Areas/experiments"
alias ..="cd ../"

alias pu="phpunit"
alias pf="phpunit --filter"

# gls --color --group-directories-first --time-style=long-iso --human-readable -o --almost-all --directory * .*, considering
alias ls="exa --long --color-scale --all --group-directories-first --binary --time-style long-iso"
alias ll="ls"

# TODO make prettier and stuff
j() {
    projects_dir="$HOME/Projects"
    areas_dir="$HOME/Areas"

    finder_cmd="fd --max-depth=2 \
      --type=directory \
      --search-path=$HOME/Areas \
      --search-path=$HOME/Projects"

    local jump
    jump=$(eval "$finder_cmd" | fzf) && cd "$jump"
}
#################

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
