# Fig pre block. Keep at the top of this file.
[[ -f "$HOME/.fig/shell/zshrc.pre.zsh" ]] && builtin source "$HOME/.fig/shell/zshrc.pre.zsh"

# we try to follow it a little bit but not really
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"

export ZSH_COMPDUMP="${ZSH_CACHE_DIR}/.zcompdump-${(%):-%m}-${ZSH_VERSION}"

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

typeset -U path
path=(
    /opt/homebrew/bin
    $XDG_CONFIG_HOME/emacs/bin
    $HOME/.local/bin
    $path
)

source /opt/homebrew/share/antigen/antigen.zsh

antigen bundle zsh-users/zsh-autosuggestions
antigen bundle jeffreytse/zsh-vi-mode

antigen theme romkatv/powerlevel10k

antigen apply

export ZVM_INSERT_MODE_CURSOR=$ZVM_CURSOR_BLINKING_BEAM

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

export EDITOR=nvim
export GIT_EDITOR=nvim

alias vim="nvim"
alias g="git"
alias gs="git status"
## TODO make these smarter functions
alias ga="git add"
alias gap="git add --patch"
alias gc="git commit"
alias gp="git push"
alias gd="git diff"
alias gco="git checkout"
alias nah="git reset --hard head && git clean -fd"

alias dotfiles="cd ~/Areas/dotfiles"
alias dmd="cd ~/.config/doom"

alias home="cd ~"
alias desk="cd ~/Desktop"
alias p="cd ~/Projects"
alias exp="cd ~/Areas/experiments"
alias ..="cd ../"

alias ls="exa --long --color-scale --all --group-directories-first --binary --time-style long-iso"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Fig post block. Keep at the bottom of this file.
[[ -f "$HOME/.fig/shell/zshrc.post.zsh" ]] && builtin source "$HOME/.fig/shell/zshrc.post.zsh"
