#!/bin/zsh

cd "$(dirname "${BASH_SOURCE[0]}")"

display_height=$(yabai -m query --displays --display | jq -r '.frame.h')
display_width=$(yabai -m query --displays --display | jq -r '.frame.w')
display_ratio=$(echo "$display_width / $display_height" | bc -l)
is_ultrawide=$(echo "$display_ratio > 2" | bc -l)

if [ $is_ultrawide -eq 1 ]; then
    ./window_left_half
else
    ./window_left_half
fi
