#!/bin/zsh

#### config stuff
space_id=$(yabai -m query --spaces --space | jq -r '.id')

top_padding=$(yabai -m config --space $space_id top_padding)
bottom_padding=$(yabai -m config --space $space_id bottom_padding)
right_padding=$(yabai -m config --space $space_id right_padding)
left_padding=$(yabai -m config --space $space_id left_padding)

x_padding=8
y_padding=8

menubar_height=40
dock_height=50
#####

display_width=$(( $(yabai -m query --displays --display | jq -r '.frame.w') - (2 * x_padding) ))
display_height=$(( $(yabai -m query --displays --display | jq -r '.frame.h') - (2 * y_padding) - menubar_height - dock_height ))

desired_width=$(( (display_width / 2) - x_padding ))
desired_height=$display_height

x_pos=${x_padding}
y_pos=$(( menubar_height + y_padding ))

yabai -m window --move "abs:${x_pos}:${y_pos}"
yabai -m window --resize "abs:${desired_width}:${desired_height}"
