#!/bin/zsh

cd "${0:a:h}"

display_height=$(yabai -m query --displays --display | jq -r ".frame.h")
display_width=$(yabai -m query --displays --display | jq -r ".frame.w")
display_ratio=$(echo "$display_width / $display_height" | bc -l)
is_ultrawide=$(echo "$display_ratio > 2" | bc -l)

# --grid <rows>:<cols>:<start-x>:<start-y>:<width>:<height>

if [ $is_ultrawide -eq 1 ]; then
    # center main portion
    yabai -m window --grid 1:6:1:0:4:1
else
    # maximize
    yabai -m window --grid 1:1:0:0:1:1
fi


# 2 is big, 1 is small
